source "https://rubygems.org"

gem "mechanize", "~> 2.4"
gem "rack", "~> 1.6"
gem "rack-timeout", "~> 0.4"
gem "rest-client", "~> 2.0"
gem "tilt", "~> 2.0"
gem "slim", "~> 3.0"
gem "sass", "~> 3.4"
gem "sinatra", "~> 1.4"
gem "sinatra-flash", "~> 0.3"
gem "sinatra-redirect-with-flash", "~> 0.2"
gem "sinatra-reloader", "~> 1.0"
gem "puma"

group :development do
  gem "byebug", "~> 9.0"
  gem "shotgun", "~> 0.9"
  gem "better_errors", "~> 2.1"
  gem "git", "~> 1.3"
end

group :production do
  gem "rack-google-analytics", "~> 1.2"
end

group :test do
  gem "rake", "~> 11.2"
  gem "rack-test", "~> 0.6"
  gem "capybara", "~> 2.7"
  gem "coveralls", "~> 0.8"
  gem "rspec", "~> 3.5"
  gem "rubocop", "~> 0.42"
  gem "factory_girl", "~> 4.7"
end
